CREATE TABLE IF NOT EXISTS '%s' 
('ID' VARCHAR(32), 
Kills INT(9) NOT NULL DEFAULT 0,
Deaths INT(9) NOT NULL DEFAULT 0,
Money INT(9) NOT NULL DEFAULT 0,
TimePlayed INT(9) NOT NULL DEFAULT 0,
IsAdmin BIT NOT NULL DEFAULT 0
)